# This script is an edited version of the example found at
# https://git.ligo.org/lscsoft/example-ci-project/blob/python/.gitlab-ci.yml
# Each 0th-indentation level is a job that will be run within GitLab CI
# The only exception are a short list of reserved keywords
#
# https://docs.gitlab.com/ee/ci/yaml/#gitlab-ci-yml

# stages is a reserved keyword that defines job dependencies and
# parallelization. each stage runs in parallel but must complete
# before the next stage begins

stages:
  - test
  - deploy

.test-python: &test-python
  stage: test
  image: python
  before_script:
    # this is required because pytables doesn't use a wheel on py37
    - apt-get -yqq update
    - apt-get -yqq install libhdf5-dev
  script:
    - python -m pip install .
    - python -c "import bilby"
    - python -c "import bilby.core"
    - python -c "import bilby.core.prior"
    - python -c "import bilby.core.sampler"
    - python -c "import bilby.gw"
    - python -c "import bilby.gw.detector"
    - python -c "import bilby.gw.sampler"
    - python -c "import bilby.hyper"
    - python -c "import cli_bilby"
    - for script in $(pip show -f bilby | grep "bin\/" | xargs -I {} basename {}); do
          ${script} --help;
      done

# test basic setup on python3
basic-3.7:
  <<: *test-python
  image: python:3.7

# test example on python 3.7
python-3.7:
  stage: test
  image: bilbydev/v2-dockerfile-test-suite-python37
  script:
    - python -m pip install .

    # Run pyflakes
    - flake8 .

    # Run tests and collect coverage data
    - pytest --cov=bilby
    - coverage html
    - coverage-badge -o coverage_badge.svg -f

    # Make the documentation
    - cd docs
    - make clean
    - make html

  artifacts:
    paths:
      - htmlcov/
      - coverage_badge.svg
      - docs/_build/html/

# test example on python 3.6
python-3.6:
  stage: test
  image: bilbydev/v2-dockerfile-test-suite-python36
  script:
    - python -m pip install .

    - pytest

# Tests run at a fixed schedule rather than on push
scheduled-python-3.7:
  stage: test
  image: bilbydev/bilby-test-suite-python37
  only:
    - schedules
  script:
    - python -m pip install .

    # Run tests which are only done on schedule
    - pytest test/example_test.py
    - pytest test/gw_example_test.py
    - pytest test/sample_from_the_prior_test.py

pages:
  stage: deploy
  dependencies:
    - python-3.7
  script:
    - mkdir public/
    - mv htmlcov/ public/
    - mv coverage_badge.svg public/
    - mv docs/_build/html/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
